### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by ghost** [Atelier-Shiori/Shukofukurou-iOS#1]
Any chance of a dark theme in a future release?

...

Also. Thank you for your work. I try to go open source where I can, even on iOS.

**Comment by moyitpro** [comment]
There is a [drop in solution](https://github.com/draveness/DKNightVersion0, but if I can figure it out, I will eventually implement it in a future version.

**Comment by moyitpro** [comment]
![screen shot 2019-01-27 at 12 10 50 am](https://user-images.githubusercontent.com/161183/51796882-30f43f80-21c8-11e9-9c13-744ba02d6e3b.png)
![screen shot 2019-01-27 at 12 11 06 am](https://user-images.githubusercontent.com/161183/51796884-33ef3000-21c8-11e9-8007-41a4d0fd444f.png)

I implemented it in possibly 1.1.4 release. Still need to polish it though, but it will be in the next release.

https://github.com/Atelier-Shiori/Shukofukurou-iOS/commit/7be9a8347e4f7171106c919318c375dc334d44dc
