### ISSUE TITLE
White Splash Screen on Dark Mode 

### ISSUE THREAD

**Issue by Kosezu** [Atelier-Shiori/Shukofukurou-iOS#10]
There’s a white splash screen when launching the app in dark mode. 

**To Reproduce**
Launch app after dark mode is turned on. 

**Expected behavior**
A black or dark splash screen.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 13.2
 - Version 2.0 (latest TestFlight)

**Additional context**

**Comment by moyitpro** [comment]
<img width="486" alt="2019-10-26_21-50-10" src="https://user-images.githubusercontent.com/161183/67628364-98641c00-f83a-11e9-8aa9-8d8987d567a2.png">

fixed with https://github.com/Atelier-Shiori/Shukofukurou-iOS/commit/6feebaa4a01dd12538a3020bb67b2c4db5bc9c10
