### ISSUE TITLE
Manga toplist is empty (myanimelist)

### ISSUE THREAD

**Issue by bornout** [Atelier-Shiori/Shukofukurou-iOS#16]
**Describe the bug**
The toplist for mangas is empty if you use myanimelist as service. Anime works.

**To Reproduce**
Trending > Manga

**Screenshots**
![A9BE5A2B-3504-49D2-A4C8-D0DF0CCF6870](https://user-images.githubusercontent.com/1838271/77256267-6fbb4380-6c6d-11ea-98f1-071fa1d7918e.png)

**Smartphone (please complete the following information):**
 - Device: iPhone XS max
 - OS: iOS 13.3.1
 - Version Shukofukurou Testflight 2.0.6 (20200318)

**Comment by moyitpro** [comment]
fixed with https://github.com/Atelier-Shiori/Shukofukurou-iOS/commit/a6f3106543f4007e7be1de66809b9541f950b337
