### ISSUE TITLE
Some functions not working

### ISSUE THREAD

**Issue by lvndota2** [Atelier-Shiori/Shukofukurou-iOS#18]
**Describe the bug**
Search/Season function not working properly. 
**Expected behavior**
I expect being able to search anime using the app. 
**Smartphone (please complete the following information):**
 - Device: iPhone 6s
 - OS: iOS 13
 - Version 2.0.7

**Additional context**
When I try to use the Search function there is nothing showing. Even on seasons no anime was showing. I tries re-installing but still the same problem. I am using mal source. Hope this gets fixed

**Comment by moyitpro** [comment]
I just discovered the bug and have fixed it. https://github.com/Atelier-Shiori/Hakuchou/commit/e1a7d6a1522ea1d7adbe31c84fedf89002175eaa

I seem to have used the wrong dictionary when checking for the NSFW functionality. I have checked and this bug only affected MyAnimeList. I already submitted 2.0.8, which fixes this issue and waiting for Apple to approve it on TestFlight before submitting to the App Store. The update should come in 1-2 days depending on how fast Apple approves the update.
