### ISSUE TITLE
‘Days Spent’ not updating

### ISSUE THREAD

**Issue by lvndota2** [Atelier-Shiori/Shukofukurou-iOS#20]
**Describe the bug**
“Days Spent” is not updating.
Source: MAL

**To Reproduce**
1. Go to app
2. Tap on three lines on the top-most left
3. In the middle of logout and service, tap the gear logo>view list stats. 

**Expected behavior**
As expected, it should update the days spent like the stats on MAL

**Screenshots**
![E83146E2-CB64-4429-A90E-851F0366B5D1](https://user-images.githubusercontent.com/66034462/83334048-64703e00-a2d6-11ea-93a0-4a8bb6cc5cbc.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone 6s
 - OS: iOS 13
 - Version 2.0.8

**Additional context**
Have noticed this prior to update to 2.0.8. I really do appreciate the app and have recommended it to my iOS friends user. Hoping to get this fix really soon. Kudos

**Comment by moyitpro** [comment]
Fixed 
![Screen Shot 2020-06-09 at 6 04 55 PM](https://user-images.githubusercontent.com/161183/84205880-0e408f00-aa7c-11ea-8c85-253a75463f87.png)

https://github.com/Atelier-Shiori/Shukofukurou-iOS/commit/d6cfc5c32f7d262d0984229934139608a5e153db

https://github.com/Atelier-Shiori/Hakuchou/commit/96af601d3285c2a8135983c941c12ac861dd3a61
