### ISSUE TITLE
Ask for score after completing a show

### ISSUE THREAD

**Issue by pandito** [Atelier-Shiori/Shukofukurou-iOS#21]
Hi,

It would be nice, after setting a show as complete (or markgin the last episode as seen) to get an option to set a score for it.

Actually, it only marks it as complete. And then i need to look for the show again in the completed section to set a score

**Comment by moyitpro** [comment]
A prompt will be added in 3.x along with competing a title by incrementing a title, which is the last version.

**Comment by pandito** [comment]
Love it!, thank you

**Comment by moyitpro** [comment]
Implemented with https://github.com/Atelier-Shiori/Shukofukurou-iOS/commit/b26d7756c34b64a099f93f7ecc42ed3153c79c47
