### ISSUE TITLE
Anime title not appearing in search results or season sections

### ISSUE THREAD

**Issue by Marius-Muis** [Atelier-Shiori/Shukofukurou-iOS#24]
Description:
After searching for the show “Tower of God” (“Kami no Tou” or “Kami no Tō”), no results pop up. Even after looking for it in the Spring 2020 section, it did not show up. The only way I could add the show to my library was by manually adding it on the MAL website. 

Reproduce:
Search for show via search function or manually looking through the seasons section.

Device and versioning info:
 - Device: iPhone 6
 - OS: iOS 12.3.1
 - Version 2.1
 - Service: MyAnimeList

**Comment by moyitpro** [comment]
This may have to do with the classification in the MAL API as this title shows up in Anilist and Kitsu. I will investigate this during the weekend.

Sent from my iPhone 11 Pro
(Shijou Takane - 四条貴音)

**Comment by moyitpro** [comment]
Ever since we change the rating to 17+, it seems that grey area titles might still be filtering. I will make sure that we are only filtering only for hentai titles as those are definitely not allowed.

**Comment by moyitpro** [comment]
After further investigation, it seems that the filtering is happening on the API side (nothing done on the app code itself) and probably the application API key is set to filter grey area titles. I need to ask the MAL API staff about this.

**Comment by moyitpro** [comment]
It’s now fixed. It seems that some titles are automatically being marked as NSFW on MAL API. Here is the response I got back from kineta.

@chikorita157 This one should be solved now. We're having some problems with what's being automatically labelled as NSFW, so if you encounter any others like that, please just give us a ping.  It's affecting us on our end, too.

I will close this issue


Sent from my iPhone 11 Pro
(Shijou Takane - 四条貴音)
