### ISSUE TITLE
Can't log in to MyAnimeList

### ISSUE THREAD

**Issue by anoriqq** [Atelier-Shiori/Shukofukurou-iOS#26]
**Describe the bug**
I get a 404 page when I try to log in to MyAnimeList.

**To Reproduce**
1. Select MyAnimeList from the Service selector.
2. Tap Login
3. "Shukufukurou-IOS" Wants to Use "myanimelist.net" to Sign In will be asked.
4. Tap Continue
5. I get a 404 page and cannot log in.

**Expected behavior**
The MyAnimeList login page will appear in the in-app browser, and you will be asked to confirm access to the application after logging in.

**Screenshots**
![Image from iOS (2)](https://user-images.githubusercontent.com/33250012/102841867-145ef180-4449-11eb-9bd8-0e630af76844.png)
![Image from iOS (3)](https://user-images.githubusercontent.com/33250012/102841880-17f27880-4449-11eb-9f08-7a35743662f1.png)

**Smartphone (please complete the following information):**
 - Device: iPhone7
 - OS: iOS14.2
 - Version 2.1.2(Build 20201213

Reproduces on iPad as well

**Additional context**
I haven't logged in once since I first installed it.
All settings are default.

**Comment by anoriqq** [comment]
It looks like you're requesting `https://myanimelist.net/v3/oauth2/authorize`, but it appears to work if you request `v1`

**Comment by moyitpro** [comment]
Thanks, I have submitted a fixed version and hopefully it will get approved on the AppStore later today. I have tested and the new version goes to the right URL.

Sent from my iPhone 11 Pro
(Shijou Takane - 四条貴音)

**Comment by moyitpro** [comment]
2.1.3 is now approved on the App Store with the fix and it should become available shortly. I will be closing this issue.
