### ISSUE TITLE
App crashes when searching for a Manga (MAL service)

### ISSUE THREAD

**Issue by montesfjose** [Atelier-Shiori/Shukofukurou-iOS#28]
https://user-images.githubusercontent.com/43690521/103453437-f6df2280-4ca7-11eb-8041-a5abf952ff1f.MP4

The crash only happens when the search term is at least 3 characters long.

**Comment by moyitpro** [comment]
Found out the issue. I am going to need to generate a URL instead of submitting the search parameters as a url encoded form. I will have this fixed in a few days as I am still taking a break and I am not physically at my Mac to debug the iOS app on my device.

**Comment by moyitpro** [comment]
It seems that the v3 search API is too unstable at the moment since it sometimes don't return anything, thus causes the app to crash. Reverting to v2 at least for search for now.

**Comment by moyitpro** [comment]
The release is out, which reverted the search API. I have tested and the crash doesn't happen anymore.

**Comment by montesfjose** [comment]
Awesome! Thanks a ton
