### ISSUE TITLE
App won't update a manga that has the "Hiatus" status (MAL)

### ISSUE THREAD

**Issue by montesfjose** [Atelier-Shiori/Shukofukurou-iOS#29]
https://user-images.githubusercontent.com/43690521/105908132-dd55a000-5ff3-11eb-9306-77e8c6557c7f.mp4

The slide out options are the first tell that it won't allow you to update the manga. No increments by chapter or by volume. When going into the page itself, hitting "Update entry" does not do anything. Promise neverland updates just fine, however (it is not on hiatus.) I could also replicate this with the manga "Nana" (another manga on hiatus).

**Comment by moyitpro** [comment]
I don't know if it's because the title is on hiatus that its causing the issue, but I will investigate that issue this weekend when I have free time.

**Comment by moyitpro** [comment]
Fixed, a release with this fix will be coming out soon.

https://github.com/Atelier-Shiori/Shukofukurou-iOS/commit/087e4126e9f27099c87b08cfe2ae83b00a4edb40
