### ISSUE TITLE
Add AniList Episode Countdowns

### ISSUE THREAD

**Issue by cluegithub** [Atelier-Shiori/Shukofukurou-iOS#30]
I recently switched to Shukofukurou because of the feature set that better fit my needs, but one thing I miss is not having the new episode countdowns for airing shows listed at the front page. This was also one of the reasons I switched to AniList, and since MyAniList (my previous app) has this functionality (screenshot) then it should be available from AniList's API. I've also posted a quick mockup of what this functionality could look like on Shukofukurou.

![MyAniList homepage](https://user-images.githubusercontent.com/42914403/116012614-8d3da800-a5f9-11eb-8500-f3ad4a657fb9.PNG)
![Quick Mockup](https://user-images.githubusercontent.com/42914403/116012618-92025c00-a5f9-11eb-8a5f-db7b8fb8dd8c.PNG)

**Comment by moyitpro** [comment]
Its certainly possible as we are using the API to provide airing notifications. The tricky part is showing the airing date countdown on all three services as AniList only provides this data and not Kitsu and MyAnimeList. It will be tricky, but certainly doable, probably in a future release.

**Comment by moyitpro** [comment]
Implemented with https://github.com/Atelier-Shiori/Shukofukurou-iOS/commit/fe3b293f283705f5d6cd34949b0619bbb3d202d6
