### ISSUE TITLE
Display Number of Aired Episodes

### ISSUE THREAD

**Issue by Hjax** [Atelier-Shiori/Shukofukurou-iOS#31]
I see that a countdown to the next episode was added in response to #30, would it be possible to add a setting to express this data in a slightly different way, namely to display shows as Watched/Released/Total instead of just Watched/Total. For instance if 5 out of 12 episodes have been released, and I have seen 3 of them it would display 3/5/12.

**Comment by moyitpro** [comment]
Considering that there is already a lot of information, this will be too confusing to the normal user. I can add some text to the progress if a user is behind an episode.

**Comment by Hjax** [comment]
That would probably be fine, coming from Android to iOS I miss how convenient it was to see if I was caught up on a show and how many episodes were unwatched in anyme. Just having the airing episode countdown does help a lot but it feels more straightforward to display the number of released episodes somewhere, even if you had to enable it in the settings to keep the default layout less information dense.

**Comment by moyitpro** [comment]
Added a favor text when a user is behind 1 or more episodes.
![2021-06-06_09-16-40](https://user-images.githubusercontent.com/161183/120925864-8dc16800-c6a8-11eb-9469-dd9df47425a0.png)
https://github.com/Atelier-Shiori/Shukofukurou-iOS/commit/91eb3661592d654a4acaf1d8a538dd46c2aaec28
